apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsa-frontend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsa-frontend
  template:
    metadata:
      labels:
        app: dsa-frontend
    spec:
      containers:
        - name: dsa-frontend
          image: shivamk001/dsa-frontend
          env:
            - name: NEXT_PUBLIC_DSA_API_URL
              value: 'http://dsa-backend-srv:3000'
---

apiVersion: v1
kind: Service
metadata:
  name: dsa-frontend-srv
spec:
  selector:
    app: dsa-frontend
  ports:
    - name: dsa-frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
