export const enum Topics {
    Array = 'array',
    LinkedList = 'linked-list',
    Stack = 'stack',
    Queue = 'queue',
    Deque = 'deque',
    HashTable = 'hash-table',
    Set = 'set',
    Map = 'map',
    Tree = 'tree',
    BinaryTree = 'binary-tree',
    BinarySearchTree = 'binary-search-tree',
    AVLTree = 'avl-tree',
    Heap = 'heap',
    Trie = 'trie',
    Graph = 'graph',
    DirectedGraph = 'directed-graph',
    UndirectedGraph = 'undirected-graph',
    Matrix = 'matrix',
    SegmentTree = 'segment-tree',
    FenwickTree = 'fenwick-tree', // Also called Binary Indexed Tree
    SkipList = 'skip-list',
    Greedy = 'GreedyAlgorithm',
    Recursion = 'recursion',
    BinarySearch = 'binary-search',
    String = 'string',
    DynamicProgramming = 'dynamic-programming',
    
}
