apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsa-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsa-mongo
  template:
    metadata:
      labels:
        app: dsa-mongo
    spec:
      containers:
        - name: dsa-mongo
          image: mongo

---

apiVersion: v1
kind: Service
metadata:
  name: dsa-mongo-srv
spec:
  selector:
    app: dsa-mongo
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
